##################################
# NRPE DOWNLOAD & INSTALLATION
##################################
- name: Download the NRPE tarball
  get_url:
    url: "https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-{{ nrpe_version }}/nrpe-{{ nrpe_version }}.tar.gz"
    #https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.1.0/nrpe-4.1.0.tar.gz
    dest: "{{ download_dir }}/nrpe-{{ nrpe_version }}.tar.gz"

- name: Extract the NRPE tarball
  unarchive:
    src: "{{ download_dir }}/nrpe-{{ nrpe_version }}.tar.gz"
    dest: "{{ download_dir }}"
    remote_src: yes

- name: Compile and install NRPE
  shell:
    cmd: |
      ./configure &&
      make check_nrpe &&
      make install-plugin
  args:
    chdir: "{{ download_dir }}/nrpe-{{ nrpe_version }}"

- name: Create /etc/nrpe directory
  file:
    path: /usr/local/nagios/etc
    state: directory

- name: Ensure allowed_hosts line is in the file
  lineinfile:
    path: /usr/local/nagios/etc/nrpe.cfg
    line: "allowed_hosts=127.0.0.1,10.1.6.4"
    create: yes 

- name: Enable and start the NRPE service
  systemd:
    name: nrpe
    enabled: yes
    state: started