---
###########
# API
###########
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - net-tools
    - mysql-client
    - openjdk-17-jdk
    - maven

- name: Add line to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop:
    - "10.0.1.10 ehealth_web"
    - "10.0.1.11 ehealth_db"
    - "10.0.1.12 ehealth_api" 

- name: Remove directory /var/tmp/api if it exists
  command: sudo rm -rf /var/tmp/api
  ignore_errors: true           
- name: Clone Eclipse Project
  command: >
    sh -c '
      git clone --branch=main --filter=blob:none --sparse https://github.com/ReC82/EHealthFull.git /var/tmp/api &&
      cd /var/tmp/api &&
      git sparse-checkout set Eclipse/Ehealth/*
    '
  environment:
    GIT_TERMINAL_PROMPT: "0"
- name: Set executable permission on mvnw script
  become: true
  file:
    path: /var/tmp/api/Eclipse/Ehealth/mvnw
    mode: "+x"
- name: Change directory to the Maven project and Compile Java
  become: true
  shell: cd /var/tmp/api/Eclipse/Ehealth/ && sudo ./mvnw clean package
- name: Create the finale api directory
  file:
    path: /var/www/api/
    state: directory
- name: Copy JAR file
  copy:
    src: /var/tmp/api/Eclipse/Ehealth/target/Ehealth-0.0.1-SNAPSHOT.jar
    dest: /var/www/api/ehealth_api.jar
    remote_src: yes
- name: Create the Api service
  become: true
  template:
    src: ehealth_api.service.j2
    dest: /etc/systemd/system/ehealth_api.service
- name: Reload systemd to read the new service file
  become: true
  systemd:
    daemon_reload: yes
- name: Enable and start ehealth service
  systemd:
    name: ehealth_api
    enabled: yes
    state: started        