- name: Playbook for WebApplication
  hosts: all
  become: yes
  roles:
    - common
    - common_nrpe    

- name: Playbook for WebApplication
  hosts: node-web
  become: yes
  roles:
    - nginx
    - api
  # - app

- name: Playbook for Databases
  hosts: node-db
  become: yes
  roles:
    - nginx
    - mysql
    # - api
