require 'csv'

servers = []

CSV.foreach("servers.csv", headers: true) do |row|
  if true
    servers << {
      :server_hostname => row["server_hostname"],
      :server_ip => row["server_ip"],
      :env => row["env"],
      :server_function => row["server_function"],
      :server_box => row["server_box"],
      :ssh_port => row["ssh_port"],
      :http_port => row["http_port"]
    }
  end
end

# Create Ansible inventory file
File.open("inventory.ini", "w") do |file|
  servers.each do |server|
    file.puts "#{server[:server_hostname]} ansible_host=#{server[:server_ip]} ansible_port=#{server[:ssh_port]} ansible_user=vagrant"
  end
end

Vagrant.configure("2") do |config|
  servers.each do |server|
    config.vm.define server[:server_hostname] do |srv|

      # COMMON CONFIG
      srv.vm.box = server[:server_box]
      srv.vm.hostname = server[:server_hostname]
      srv.vm.network "private_network", ip: server[:server_ip]
      srv.vm.network "forwarded_port", guest: 22, host: server[:ssh_port], id: "ssh"
      config.vm.synced_folder "./shared_folder", "/home/vagrant/shared"

      # PROVISION COMMON
      # srv.vm.provision "shell", run: "always", path: "scripts/setup_common.sh"

      case server[:server_function]
      when "NODE"
        if server[:server_hostname].include?("web")
          # NETWORK
          srv.vm.network "forwarded_port", guest: 80, host: server[:http_port], id: "http"

          # CONFIG
          srv.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--memory", server[:ram]]
            vbox.customize ["modifyvm", :id, "--cpus", server[:cpu]]
          end

        elsif server[:server_hostname].include?("db")
          # CONFIG
          srv.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--memory", server[:ram]]
            vbox.customize ["modifyvm", :id, "--cpus", server[:cpu]]
          end
        end

      when "CONTROL"
        # NETWORK
        srv.vm.network "forwarded_port", guest: 8080, host: server[:http_port], id: "http"

        # PROVISIONING
        srv.vm.provision "shell", run: "always", path: "scripts/setup_control.sh"

        # CONFIG
        srv.vm.provider :virtualbox do |vbox|
          vbox.customize ["modifyvm", :id, "--memory", server[:ram]]
          vbox.customize ["modifyvm", :id, "--cpus", server[:cpu]]
        end

      when "AGENT"
        # CONFIG
        srv.vm.provider :virtualbox do |agent|
          agent.customize ["modifyvm", :id, "--memory", server[:ram]]
          agent.customize ["modifyvm", :id, "--cpus", server[:cpu]]
        end

      else
        # CONFIG MONITOR & QUALITY
        srv.vm.provider :virtualbox do |checkers|
          checkers.customize ["modifyvm", :id, "--memory", server[:ram]]
          checkers.customize ["modifyvm", :id, "--cpus", server[:cpu]]
        end

      end # END OF CASE

    end # END OF config.vm.define
  end # END OF servers.each
end # END OF Vagrant.configure("2")
