- name: Playbook for Quality Control Server
  hosts: quality-control 
  become: true
  roles:
    - common
    - common_nrpe
    - postgre
    - adoptium
    - kernel_tune
    - sonarqube
    - jmeter
    - owasp
    - node_exporter