##############################
#   install java compiler
##############################
- name: Install java sdk
  apt:
    name: openjdk-17-jdk # Check the version
    state: present

################################
# Install ZAP (Owasp)
################################

- name: Add OWASP ZAP APT repository
  apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_22.04/ /'
    state: present
    filename: 'home_cabelo'

- name: Download the OpenSUSE GPG key
  get_url:
    url: https://download.opensuse.org/repositories/home:cabelo/xUbuntu_22.04/Release.key
    dest: /tmp/Release.key
    mode: '0644'

- name: Ensure /tmp/Release.gpg is removed
  file:
    path: /tmp/Release.gpg
    state: absent

- name: Convert GPG key to binary format
  command: gpg --dearmor -o /tmp/Release.gpg /tmp/Release.key

- name: Move the key to apt's trusted key directory
  copy:
    src: /tmp/Release.gpg
    dest: /etc/apt/trusted.gpg.d/home_cabelo.gpg
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: Clean up temporary files
  file:
    path: /tmp/Release.key
    state: absent

- name: Clean up temporary GPG files
  file:
    path: /tmp/Release.gpg
    state: absent

- name: Update APT cache
  apt:
    update_cache: yes 

- name: Install OWASP ZAP
  apt:
    name: owasp-zap
    state: present