
 ##############################
 #   udpate ubuntu
 ##############################
- name: "apt-get update -y"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    
##############################
#   install java compiler
##############################
- name: Install java sdk
  shell: apt-get -y install openjdk-17-jdk # Check the version

- name: Install maven
  shell: apt-get -y install maven # Check the version

- name: Install git
  shell: apt-get -y install git

##############################
# Install Docker
##############################
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
    
##############################
#   install ufw
##############################

- name: Install ufw 
  shell: apt-get install ufw -y 

- name: Allow SSH connections on port 22
  shell: ufw allow 22/tcp comment 'Allow SSH'

- name:  Enabled firewall ufw
  shell: ufw --force enable  