- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL Service is Running
  service:
    name: mysql
    state: started

- name: Ensure MySQL databases are present.
  mysql_db:
    name: moreless
    collation: utf8_general_ci
    encoding: utf8
    state: present
    target: omit  

- name: Create a MySQL User
  mysql_user:
    name: {{ db_user }}  # Name of the new user
    password: {{ db_pass: }}  # User's password
    priv: "moreless.*:ALL"  # All privileges on the specified database
    state: present  # Ensure the user exists