##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest
  notify: Restart MySQL  # Notify to restart MySQL after installation

##############################
#   Secure MySQL Installation (Optional)
##############################
- name: Secure MySQL Installation
  command: "mysql_secure_installation"
  args:
    stdin: |
      n  # Set root password (optional, if needed)
      y  # Remove anonymous users
      y  # Disallow root login remotely
      y  # Remove test database
      y  # Reload privilege tables

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL Service is Running
  service:
    name: mysql
    state: started
  notify: Restart MySQL  # Restart MySQL if needed