##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: 
    - mysql-server
    - mysql-client
    - python3-pip
    state: present
    update_cache: yes

######################################
# INSTALL MYSQL DEPEDENCIES
######################################    

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes

- name: Update mysql password for superuser `{{ mysql_superuser }}`
  mysql_user:
    # Update the superuser to have all grants and a password
    name: "{{ mysql_superuser }}"
    host: localhost
    password: "{{ mysql_superuser_password }}"
    priv: "*.*:ALL,GRANT"
    # Login *as root* to perform this change, even though you might
    # be altering the root user itself
    login_user: root
    login_password: ""
    login_port: "{{ mysql_port }}"
    login_host: localhost
    login_unix_socket: "{{ mysql_socket }}"
    # As a good measure,have ansible check whether an implicit login
    # is possible first
    check_implicit_admin: yes

- name: Add user to access "moreless" database
  mysql_user:
    name: "{{ mysql_moreless_user }}"
    host: localhost
    password: "{{ mysql_moreless_password }}"
    priv: "moreless.*:ALL"
    login_user: "{{ mysql_superuser }}"
    login_password: "{{ mysql_superuser_password }}"
    login_port: "{{ mysql_port }}"
    login_host: localhost
    login_unix_socket: "{{ mysql_socket }}"
    check_implicit_admin: yes    

- name: Create system-wide mysql configuration file
  template:
    src: system_wide_mysql.cnf.j2
    dest: /etc/my.cnf

- name: Create mysql configuration file for `{{ mysql_superuser }}`
  template:
    src: root.my.cnf.j2
    dest: "{{ mysql_superuser_home }}/.my.cnf"
  notify:
  - Restart Mysql    