- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL Service is Running
  service:
    name: mysql
    state: started

- name: Create user
  mysql_user:
    name: "moreless"
    login_host: localhost
    login_user: "api_user"
    login_password: "api_user"
    state: present

- name: Create a MySQL User
  mysql_user:
    name: api_user  # Name of the new user
    password: api_user  # User's password
    priv: "moreless.*:ALL"  # All privileges on the specified database
    state: present  # Ensure the user exists