- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL Service is Running
  service:
    name: mysql
    state: started

- name: update mysql root password for root account
  mysql_user:
    name: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: 'localhost'
    password: 'root'
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true

- name: Create user
  mysql_db:
    name: "moreless"
    state: present

- name: Create a MySQL User
  mysql_user:
    name: api_user
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: 'localhost'
    password: 'api_user'
    check_implicit_admin: true
    priv: "moreless.*:ALL"
    state: present