- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL Service is Running
  service:
    name: mysql
    state: started

- name: update mysql root password for all root accounts  
  mysql_user:  
    name: root  
    host: "{{ item }}"  
    password: "{{ mysql_root_password }}"  
    login_user: root  
    login_password: "{{ mysql_root_password }}"  
    check_implicit_admin: yes  
    priv: "*.*:ALL,GRANT"  
    with_items:  
    - "{{ ansible_hostname }}"  
    - 127.0.0.1  
    - ::1  
    - localhost

- name: create a new database  
  mysql_db: name=moreless state=present login_user=root login_password="{{ mysql_root_password }}"

- name: Create a MySQL User
  mysql_user:
    name: api_user  # Name of the new user
    password: api_user  # User's password
    priv: "moreless.*:ALL"  # All privileges on the specified database
    state: present  # Ensure the user exists