##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest
  notify: Restart MySQL  # Notify to restart MySQL if needed

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL Service is Running
  service:
    name: mysql
    state: started

- name: Create a MySQL Database
  mysql_db:
    name: moreless  # Name of the new database
    state: present  # Ensure the database is created

- name: Create a MySQL User
  mysql_user:
    name: api_user  # Name of the new user
    password: api_user  # User's password
    priv: "moreless.*:ALL"  # All privileges on the specified database
    state: present  # Ensure the user exists