##############################
#   Install MySQL
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest
  notify: Restart MySQL

# Install PyMySQL for Python 3
- name: Install PyMySQL (Python 3)
  apt:
    name: python3-pymysql
    state: present

##############################
#   Configure MySQL User
##############################
- name: Create MySQL User with Specific Privileges
  mysql_user:
    name: api_user
    password: api_user  # User's password
    login_user: root  # Root user
    login_password: root  # Root user's password
    priv: "api_db.*:ALL"  # Privileges for the user
    state: present

- name: Create MySQL Database
  mysql_db:
    name: api_db  # Name of the database
    state: present  # Ensure the database exists

##############################
#   Secure MySQL Installation
##############################
- name: Secure MySQL Installation
  command: "mysql_secure_installation"
  args:
    stdin: |
      n  # Don't set a new root password (use existing)
      y  # Remove anonymous users
      y  # Disallow root login remotely
      y  # Remove test database
      y  # Reload privilege tables    

##############################
#   UFW Configuration
##############################
- name: Allow MySQL connections on port 3306
  ufw:
    rule: allow
    port: 3306
    proto: tcp
    comment: "Allow MySQL"


