- name: Complete MySQL Installation and Configuration
  hosts: all
  become: yes  # Run tasks with elevated privileges
  tasks:
    ##############################
    #   Install MySQL Server
    ##############################
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: latest
      notify: Restart MySQL

    # Ensure MySQL Python library is installed for Ansible
    - name: Install PyMySQL (Python 3)
      apt:
        name: python3-pymysql
        state: present

    ##############################
    #   Secure MySQL Installation
    ##############################
    - name: Secure MySQL Installation
      command: "mysql_secure_installation"
      args:
        stdin: |
          y  # Set root password (change as needed)
          root_password
          y  # Remove anonymous users
          y  # Disallow root login remotely
          y  # Remove test database
          y  # Reload privilege tables

    ##############################
    #   Create MySQL User and Database
    ##############################
    - name: Create MySQL Database
      mysql_db:
        name: api_db  # Name of the database
        state: present  # Ensure it exists

    - name: Create MySQL User with Specific Privileges
      mysql_user:
        name: api_user
        password: api_user_password  # User's password
        login_user: root  # MySQL root user
        login_password: root_password  # MySQL root password
        priv: "api_db.*:ALL"  # All privileges on the created database
        state: present  # Ensure the user exists

    ##############################
    #   Configure UFW (Firewall)
    ##############################
    - name: Allow MySQL connections on port 3306
      ufw:
        rule: allow
        port: 3306
        proto: tcp
        comment: "Allow MySQL"

    ##############################
    #   Restart MySQL Service
    ##############################
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
