- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: latest

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes

- name: user setup in mysql
  mysql_user:
    user: root
    password: password
    host: localhost
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart MySQL