- name: Change system timezone
  ansible.builtin.shell:
    cmd: "timedatectl set-timezone Europe/Brussels"

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: "PyMySQL"
    state: present