- name: Change system timezone
  ansible.builtin.shell:
    cmd: "timedatectl set-timezone Europe/Brussels"

- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure PyMySQL is installed
  ansible.builtin.pip:
    name: "PyMySQL"
    state: present