
 ##############################
 #   udpate ubuntu
 ##############################
- name: "apt-get update -y"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    
##############################
#   install .NET SDK
##############################
- name: Install Dotnetsdk
  apt:
    name: dotnet-sdk-8.0
    state: present