##############################
#   install java compiler
##############################
- name: Install java sdk
  apt:
    name: openjdk-17-jdk # Check the version
    state: present

################################
# Install ZAP (Owasp)
################################

- name: Add OWASP ZAP APT repository
  apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_22.10/ /'
    state: present
    filename: 'home_cabelo'

- name: Add OWASP ZAP GPG key
  apt_key:
    url: 'https://download.opensuse.org/repositories/home:cabelo/xUbuntu_22.10/Release.key'
    state: present
    keyring: '/etc/apt/trusted.gpg.d/home_cabelo.gpg'

- name: Update APT cache
  apt:
    update_cache: yes 

- name: Install OWASP ZAP
  apt:
    name: owasp-zap
    state: present