
 ##############################
 #   udpate ubuntu
 ##############################
- name: "apt-get update -y"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    
##############################
#   install java runtinme
##############################
- name: Install Java JRE
  apt:
    name: default-jre
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Create a new user
  user:
    name: jenkins
    shell: /bin/bash
    create_home: yes

- name: Set password for the user
  ansible.builtin.shell: echo "jenkins:jenkins" | chpasswd

- name: Create Working Directory
  file:
    path: /home/jenkins/workingdir
    state: directory
    mode: "0755"