- name: Playbook for all agents
  hosts: all
  become: yes
  roles:
    - common
    - common_nrpe
    - node_exporter
    
- name: Playbook for deploying java tools
  hosts: agents-java
  become: yes
  roles:
    - maven
    - adoptium
- name: Playbook for deploying dotnet tools
  hosts: agents-dotnet
  become: yes
  roles:
    - dotnet
    - adoptium
