- name: Install required packages
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
    state: present

- name: Create keyrings directory for Grafana GPG key
  file:
    path: "/etc/apt/keyrings/"
    state: directory

- name: Download Grafana GPG key
  get_url:
    url: "https://apt.grafana.com/gpg.key"
    dest: "/tmp/grafana.gpg"

- name: Remove existing Grafana GPG key
  file:
    path: "/etc/apt/keyrings/grafana.gpg"
    state: absent

- name: Add Grafana GPG key to the keyring
  command: gpg --dearmor -o /etc/apt/keyrings/grafana.gpg /tmp/grafana.gpg

- name: Add Grafana repository with signed-by
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com/oss/deb stable main"
    state: present
    filename: "grafana"
  ignore_errors: true   

- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start Grafana service
  systemd:
    name: grafana-server
    state: started

- name: Enable Grafana service to start on boot
  systemd:
    name: grafana-server
    enabled: yes

- name: Check Grafana service status
  systemd:
    name: grafana-server
    state: started
  register: grafana_status
  ignore_errors: true

- name: Create Nginx configuration for Grafana
  copy:
    dest: "/etc/nginx/sites-available/grafana.conf"
    content: |
      server {
        listen 8666;
        server_name localhost;

        location / {
          proxy_pass http://localhost:3000/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

- name: Enable the Grafana Nginx configuration
  file:
    src: "/etc/nginx/sites-available/grafana.conf"
    dest: "/etc/nginx/sites-enabled/grafana.conf"
    state: link

- name: Restart Nginx service if configuration is valid
  systemd:
    name: nginx
    state: restarted
  when: "'syntax is ok' in nginx_configtest_result.stdout"

