---
- name: Update apt cache and install dependencies
  apt:
    update_cache: yes
    name:
      - python3
      - python3-venv
      - python3-pip
      - libpq-dev
      - nginx
      - git
    state: present

- name: Create a directory for the Django app
  file:
    path: "{{ project_dir }}"
    state: directory

- name: Create a virtual environment
  command: python3 -m venv {{ project_dir }}/venv
  args:
    creates: "{{ project_dir }}/venv/bin/activate"

- name: Install Gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ project_dir }}/venv"

- name: Create systemd socket for Gunicorn
  template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket   

- name: Create systemd service for Gunicorn
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes    

- name: Enable and start Gunicorn service
  systemd:
    name: gunicorn
    enabled: yes
    state: started

- name: Start and enable gunicorn.socket
  systemd:
    name: gunicorn.socket
    enabled: yes
    state: started

- name: Configure Nginx
  template:
    src: nginx_django.j2
    dest: /etc/nginx/sites-available/django

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/django
    dest: /etc/nginx/sites-enabled/django
    state: link

- name: Uncomment server_names_hash_bucket_size in nginx configuration
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^#\s*server_names_hash_bucket_size'
    line: 'server_names_hash_bucket_size 64;'
  notify: Reload nginx

- name: Allow NGINX Full
  ufw:
    rule: allow
    name: 'Nginx Full'

- name: Reload NGINX
  systemd:
    name: nginx
    state: reloaded