---
- name: Update apt cache and install dependencies
  apt:
    update_cache: yes
    name:
      - python3
      - python3-venv
      - python3-pip
      - libpq-dev
      - nginx
      - git
    state: present

- name: Create a directory for the Django app
  file:
    path: "{{ django_app_path }}"
    state: directory
    owner: "{{ django_user }}"
    group: "{{ django_user }}"

- name: Create a virtual environment
  command: python3 -m venv {{ django_app_path }}/venv
  args:
    creates: "{{ django_app_path }}/venv/bin/activate"

- name: Install Gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ django_app_path }}/venv"

- name: Configure Gunicorn
  template:
    src: gunicorn_start.sh.j2
    dest: "{{ django_app_path }}/gunicorn_start.sh"
    mode: '0755'
    owner: "{{ django_user }}"
    group: "{{ django_user }}"

- name: Create systemd service for Gunicorn
  template:
    src: django.service.j2
    dest: /etc/systemd/system/django.service

- name: Enable and start Gunicorn service
  systemd:
    name: django
    enabled: yes
    state: started

- name: Configure Nginx
  template:
    src: nginx_django.j2
    dest: /etc/nginx/sites-available/django
  notify: restart nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/django
    dest: /etc/nginx/sites-enabled/django
    state: link
  notify: restart nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes