- name: Add line to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop:
    - "10.0.1.10 ehealth_web"
    - "10.0.1.11 ehealth_db"
    - "10.0.1.12 ehealth_api"  
- name: Installing Mysql
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client 
    - python3-mysqldb
    - libmysqlclient-dev
    
- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes
- name: creating mysql user
  mysql_user:
    name: "dbadmin"
    password: "Th!s!s@Fuck!nGS3cr3t!"
    priv: '*.*:ALL'
    host: '%'
    state: present
- name: creating ehealth database (not mandatory)
  mysql_db:
    name: "ehealth"
    state: present
- name: Enable remote login to mysql
  lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes
  notify: # Doesn't seems to work
      - Restart mysql
- name: Install Net-Tools For Debug
  apt:
    name: net-tools
    state: present
- name: Restart Mysql Svc
  become: true
  service:
    name: mysql
    state: restarted        
 