
 ##############################
 #   udpate ubuntu
 ##############################
- name: "apt-get update -y"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Set TimeZone
  ansible.builtin.timezone:
    name: Europe/Brussels

- name: Install git
  apt:
    name: git
    state: present

##############################
#   install ufw
##############################

- name: Install ufw 
  shell: apt-get install ufw -y 

- name: Allow SSH connections on port 22
  shell: ufw allow 22/tcp comment 'Allow SSH'

- name: Allow SSH connections on port 9000
  shell: ufw allow 9000/tcp comment 'Allow SonarQube Web'

- name:  Enabled firewall ufw
  shell: ufw --force enable  